name: Check

on:

  push:
    branches:
    - '**'
    tags:
    - '**'

  pull_request: ~

  workflow_dispatch: ~

jobs:

  quality:
    name: Code QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install black flake8 isort
      - run: black --version
      - run: isort --check .
      - run: black --check .
      - run: flake8 .
